name: Hello, Actions!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, Actions!"
      - name: Show Environment Values
        env:
          MY_VALUE: my_value
        run: |
          echo ${MY_VALUE}
          echo ${CI}
          echo ${HOME}
          echo ${GITHUB_WORKFLOW}
          echo ${GITHUB_RUN_ID}
          echo ${GITHUB_RUN_NUMBER}
          echo ${GITHUB_ACTION}
          echo ${GITHUB_ACTIONS}
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_EVENT_NAME}
          echo ${GITHUB_EVENT_PATH}
          echo ${GITHUB_WORKSPACE}
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF}
