name: Security Audit
on:
  schedule:
    - cron: '40 * * * *'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node v12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Audit
        run: yarn audit
