name: Update Assets
on:
  repository_dispatch:
    types: [update-assets]

# ref: https://github.com/technote-space/technote-space/blob/master/.github/workflows/update-stats.yml

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutets: 10
    steps:
      - uses: actions/checkout@v2
      - name: Download stats
        run: |
          curl -sS -o assets/stats.svg "https://github-readme-stats.vercel.app/api?username=kawarimidoll&count_private=true&show_icons=true"
          if cat assets/stats.svg | grep -q "svg"; then echo "downloaded_flag=1" >> $GITHUB_ENV; fi

      - name: Check diff
        if: env.downloaded_flag
        run: |
          git add .
          if [ -n "$(git status --short || :)" ]; then echo "commit_flag=1" >> $GITHUB_ENV; fi
      - name: Git commit
        if: env.commit_flag
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit -qm "update asssets"
          git push origin

